site_name: loop-ed - Materiaalien kierrätys
theme:
  name: material
nav:
  - Tietoa: index.md
  - Lasi ja keramiikka: lasi_ja_keramiikka.md
  - Muovit - likaiset tai muut sekalaiset: muovit-likainen_tai_muu_sekalainen.md
  - Orgaaninen jäte: orgaaninen_jate-kompostoitava.md
  - Pahvit: pahvit.md
  - Paperit: paperit.md
  - Paristot ja pienakut: paristot_ja_pienakut.md
  - Pienmetallit: pienmetallit.md
  - Pullot ja tölkit: pullot_ja_tolkit.md
  - Sekajäte: sekajate.md
  - Tietosuojapaperit: tietosuojapaperit.md
extra_css:
  - assets/styles.css