site_name: loop-ed - Materiaalien kierrätys
theme:
  name: material
nav:
  - Tietoa: index.md
  - Akut: akut.md
  - Lasi ja keramiikka: lasi_ja_keramiikka.md
  - Muovit: muovit.md
  - Orgaaninen jäte: orgaaninen_jate.md
  - Pahvit: pahvit.md
  - Paperit: paperit.md
  - Paristot ja pienakut: paristot_ja_pienakut.md
  - Pienmetallit: pienmetallit.md
  - Pullot ja tölkit: pullot_ja_tolkit.md
  - Puut: puut.md
  - Sekajäte: sekajate.md
  - SER: ser.md
  - Vaarallinen jäte: vaarallinen_jate.md
extra_css:
  - assets/styles.css
